apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd-app
  namespace: default
spec:
  destination:
    namespace: bgd
    server: http://127.0.0.1:45827
  project: default
  source:
    path: k8s
    repoURL: https://github.com/maximilianoPizarro/application-argocd
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
