---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-pedidosrapi-flask
  name: api-pedidosrapi-flask
  namespace: api-pedidosrapi-flask
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-pedidosrapi-flask
---
