---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pedidosrapi-flask
  namespace: api-pedidosrapi-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-pedidosrapi-flask
    spec:
      containers:
      - image: quay.io/maximilianopizarro/api-pedidosrapi-flask:latest
        name: api-pedidosrapi-flask
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
